trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines&WT.mc_id=DOP-MVP-5001655
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN(b4b2e7e9-66e7-46b5-a56b-cce2b50011d4)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      param($arg1, $arg2)
      
      echo $arg1
      echo $arg2
    arguments: 'arg1 arg2'

# https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines&WT.mc_id=DOP-MVP-5001655
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      param($arg1, $arg2)
      
      echo $arg1
      echo $arg2
    pwsh: true
    arguments: 'arg1 arg2'
  condition: always()
  
# https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines&WT.mc_id=DOP-MVP-5001655
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'MSDN(b4b2e7e9-66e7-46b5-a56b-cce2b50011d4)'
    ScriptType: 'InlineScript'
    Inline: |
      param($arg1, $arg2)
      
      echo $arg1
      echo $arg2
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  condition: always()